# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table=None,
        ),
    ]
